### PR TITLE
Fix amrfinderdb dataset name

### PR DESCRIPTION
**Pull request by mehalter**
After exploring the code it seems that this dataset should be named `amrfinderdb` rather than `amrfinder`

### CODE REVIEW

**Comment by rpetit3** [comment]
Hi @mehalter 

Thank you very much for your contribution. I'm a bit bummed to tell you though, that in the next version of bactopia I have removed `bactopia datasets`.

If you are interested, here is an issue [Bactopia v3 - Help Wanted](https://github.com/bactopia/bactopia/issues/394). Otherwise check out my [dev branch](https://github.com/bactopia/bactopia/tree/dev).

Again, super bummed to be the bearer of bad news. If you have an ideas or contributions you still want to make, please don't hesitate to let me know!

Thank again, I really appreciate your effort,
Robert

**Comment by mehalter** [comment]
No worries at all @rpetit3 ! I expected that as well as I've been following the v3 development recently and have read through most of the open issues currently on the repository. Do you have a timeline on the release of the version 3 as stable? I'm with a group at GTRI helping out with some infrastructure stuff and we are trying to use bactopia as a working example for this new system. We are trying to get by with the current release and haven't made it very far 😅 If the release close to being finished and getting released soon-ish, I would be able to make the argument that testing on unreleased software would make sense in this case.

We have been on a call or two over the last little bit but I'm not sure if we've been formally introduced, so I'm sure we will be working together a bit as time goes on 😄 Cheers!

**Comment by rpetit3** [comment]
For v2, if its the `bactopia datasets` amrfinder issue that you are running into, take a look at this: https://github.com/bactopia/bactopia/issues/377

This should get you going. 

As for v3, much sooner than later (week or two). I'm updating the docs to capture v3, which is leading to a lot of writing and creating templates. I'm also taking this time to reorganize to make it easier to add to docs later (e.g .more tutorials).

Here's link to the docs in progress: https://staging.bactopia.com/

**Comment by mehalter** [comment]
Awesome that sounds amazing! Yeah I was able to get the `amrfinder` to download and after forcing an update to `ncbi-genome-download` I was able to get `bactopia datasets` fully working, but after that I was running into some new issues where `GATHER SAMPLES` was causing a lot of failures and I haven't made it past that.

If v3 is coming out in a matter of a couple weeks, that is definitely soon enough for us to just start giving that a shot instead! Thanks for linking the WIP docs

**Comment by rpetit3** [comment]
@mehalter happy to report [v3 has been released](https://github.com/bactopia/bactopia/releases/tag/v3.0.0)

Yell my way if it gives you any problems (I'm expected some due to the major release)!

**Pull request closed without merging**
