### PR TITLE
Add modules of individual processes

### PR DESCRIPTION
**Pull request by abhi18av**
This PR follows up from the work done during the last few months to modularize the monolithic `main.nf` using the DSL2 from Nextflow.

Related https://github.com/bioinformatics-lab/bactopia/issues/8 and https://github.com/bioinformatics-lab/bactopia/tree/dsl2-modules 

Please note that this is a rough start and it'd require atleast a couple iterations to be in a good shape to be merged. Davi (@Mxrcon) and I (@abhi18av ) are happy to be of help and are excited to take this forward and accomodate any changes you request.

Thanks @rpetit3 , for the awesome work on Bactopia! 🎉

### CODE REVIEW

**Comment by rpetit3** [comment]
@Mxrcon and @abhi18av super excited about this one! Thank you very much! 

I changed the merge branch to `dsl2`, I'm going to play around with it this weekend! (haha super super excited about this!)

**Comment by abhi18av** [comment]
Some things we know that would be changed during the course of this review 

- [ ] Shrim the module folders (Readme, bin, template folders etc)
- [ ] Enhance the utils to accomodate further channel manipulation
- [ ] Combine modules into sub-workflows to allow other people to choose parts they'd like to use

**Comment by Mxrcon** [comment]
@abhi18av I can take care of the usage of path instead of file! you can focus on the other tasks!

Thank you @rpetit3 for taking time to this!

**Comment by rpetit3** [comment]
Quick question, for the module bins (https://github.com/bioinformatics-lab/bactopia/tree/dsl2-modules/modules/blast/blast_genes/bin). Is it ok to delete the scripts that won't be used by the module? (e.g. update-tools.sh)

I think the answer is "yes, it's ok to remove unused scripts", but want to verify. If the answer is yes, I can go through and delete the unused scripts.

**Comment by abhi18av** [comment]
Yes, you are right it's okay to delete those module level `bin` folders if the script isn't used in that module.

Though in light of https://github.com/nextflow-io/nextflow/issues/1798, if the NF script `main.nf`  is invoked from the base directory (or outside) the module will find those scripts in `bin` folder. 

However, if you wish to test only that module, then it's best to invoke NF from that particular module itself and in that case the module level `bin` would be used by that process.

**Comment by rpetit3** [comment]
For module specific scripts I'll put them in the module `bin` folder and not the main `bactopia/bin` folder.

Like you mentioned, for testing it will be great and it should prevent maintaining duplicates (if shared across modules it will be duplicated (example: `merge-blast-json.py` is shared across the blast processes)).

---

For testing and help on my end, I had a question. On the `bioinformatics-lab/bactopia` repo, which branch are we aiming to get into bactopia, `bioinformatics-lab/dsl2-modules` or `bioinformatics-lab/dsl2`?

I'm assuming the route is `bioinformatics-lab/dsl2-modules` --> `bioinformatics-lab/dsl2` --> `bactopia/dsl2` --> `bactopia/master` 

Thank you!

**Comment by abhi18av** [comment]
I suggest that we continue working on the `dsl2-modules` branch since it doesn't contain changes to the `main.nf` and therefore we can include the modules and then iteratively swap them into the main.nf file piece-by-piece.

What do you think?

**Comment by rpetit3** [comment]
Sounds good! Thank you for clearing that up.

Next question, would you prefer my contributions come into `bioinformatics-lab/dsl2-modules` until ready to merge this PR into `bactopia/dsl2`, or go ahead and get this merged so my contributions can be made directly to `bactopia/dsl2`?

**Comment by abhi18av** [comment]
> go ahead and get this merged so my contributions can be made directly to bactopia/dsl2

I think that this makes more sense, as we can have a central point of reference. What do you think @Mxrcon ?

**Comment by Mxrcon** [comment]
> I think that this makes more sense, as we can have a central point of reference. What do you think @Mxrcon ?

I completely agree, we can track your changes on your branch and we could discuss the points mentioned by @abhi18av after you make them!

**Comment by rpetit3** [comment]
Sounds like a plan! Llet me fix the conflicting `main.nf` then I'll get this merged

**Comment by rpetit3** [comment]
This might actually be easier on your end since I cannot edit the files.

I think at the moment if you just use the most recent `main.nf` (unless there are DSL2 specific changes in the `dsl2-modules` version, I didn't notice any), this should fix the conflict.

Once merged, I'll bring the `bactopia/dsl2` branch up to v1.7.1 (the PR I closed on your end)

**Comment by abhi18av** [comment]
Okay, I've rebased this branch on the `master v1.7.1` and resolved the merge conflicts.

**Comment by abhi18av** [comment]
@rpetit3 , for collaborating further https://github.com/bactopia/bactopia/pull/228#issuecomment-864138501 , how do you think that we should proceed?

Would it make sense to use a Github project to track the work to be done/in-progress/done ?

**Comment by rpetit3** [comment]
I've started a Bactopia v2 project here https://github.com/bactopia/bactopia/projects/1

For now we can make the focus getting DSL2 fully implemented, then there's a bunch I'll want to get in as well (more bactopia tools, other random issues)

**Comment by abhi18av** [comment]
Oh, makes sense - thanks for the initiative 👍

**Pull request merged**
