### PR TITLE
Update main.nf

### PR DESCRIPTION
**Pull request by Mxrcon**
First Pull Request

### CODE REVIEW

**Comment by rpetit3** [comment]
Hi @Mxrcon,

Thanks for the PR. I've been holding off on enabling DSL2. I'm curious to get your thoughts on the benefit of enabling it, without changing anything else.

Cheers,
Robert

**Comment by Mxrcon** [comment]
I'm Sorry, I made the PR with the wrong branch. I'll Remove it

**Comment by rpetit3** [comment]
No worries! Let me know how I can help.

I'll start wrapping my head around DSL2.

**Comment by Mxrcon** [comment]
Ok, I'll tell you if I need something you can keep track of the progress on the branch that i accidentally used to create a pull request

**Comment by abhi18av** [comment]
Hi @rpetit3 , 

@Mxrcon and I are collaborating together for the modernization of the pipeline into DSL2, however at the same time we are approaching this as a learning experience for @Mxrcon , refer https://github.com/bioinformatics-lab/bactopia/issues/2#issuecomment-782000730 . It might take a little bit of time, but we'll surely raise the PR once it's ready.

Regarding the benefits of DSL2, basically after a while it'll become the default DSL in Nextflow and therefore the porting to DSL2 is more future-proof.

Moreover, the modular structure allows one to easily swap-in/out any particular process, run only a specific subsets of tools (sub-workflows) and to test each module individually.

**Comment by rpetit3** [comment]
HI @abhi18av 

No worries, I saw the PR (`nextflow.enable.dsl=2`) and thought there was a benefit to just enabling DSL2 alone without implementing any of the DSL2 features.

I totally agree though, DSL2 and many advantages and Iam planning it for v2 of Bactopia. 

@Mxrcon please don't hesitate to reach out if you have any questions about Bactopia. Let me know if there's anything i can do to help!

Thank you!
Robert

**Pull request closed without merging**
